/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const ARTIFACTS_URL =
    'https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/';

// server defaults
export const DEFAULT_PROJECT_NAME = 'my-redm-server';
export const SERVER_DIR_NAME = 'server';
export const SERVER_DATA_DIR_NAME = 'server-data';

// db config 
export const DEFAULT_DB_HOST = 'localhost';
export const DEFAULT_DB_PORT = '3306';
export const DEFAULT_DB_USERNAME = 'root';
export const DEFAULT_DB_PASSWORD = '';
export const DEFAULT_DB_NAME = 'rsg_redm';

//  server.cfg default
export const DEFAULT_SERVER_NAME = 'My RedM Server';
export const DEFAULT_MAX_CLIENTS = '32';
export const DEFAULT_SERVER_ENDPOINTS = [
    'endpoint_add_tcp "0.0.0.0:30120"',
    'endpoint_add_udp "0.0.0.0:30120"',
];

export const RECIPE_URL_HINT =
    'e.g. https://github.com/Rexshack-RedM/txAdminRecipe/blob/main/rsgcore.yaml';

// start script
export const START_SCRIPT_FILENAME = 'start.sh';
export const START_SCRIPT_CONTENT = `#!/bin/bash
# Auto-generated by tx-run
cd "$(dirname "$0")/${SERVER_DATA_DIR_NAME}"
exec bash ../${SERVER_DIR_NAME}/run.sh +exec server.cfg
`;
